kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: hUQOQNgMoaSbDLTLXm5WUr3hBV1n9Zckc9w85bu32mQ=
      - identity: {}
